import React from 'react';

export default function Podcast({ audioUrl, ticker, companyName }) {
  const hasAudio = Boolean(audioUrl);

  return (
    <section id="podcast" className="report-section">
      <h2>Samantha's Podcast</h2>
      <p className="section-subtitle">
        AI-Powered Audio Analysis by Samantha, BUSI Stock Analyst
      </p>

      <div className={`podcast-card ${!hasAudio ? 'podcast-card--disabled' : ''}`}>
        <div className="podcast-header">
          <span className="podcast-icon" aria-hidden="true">&#127908; Audio Analysis</span>
          <h3>
            {ticker ?? 'Stock'} Deep Dive{companyName ? ` \u2014 ${companyName}` : ''}
          </h3>
        </div>

        {hasAudio ? (
          <audio className="podcast-player" controls src={audioUrl}>
            Your browser does not support the audio element.
          </audio>
        ) : (
          <div className="podcast-placeholder">
            <p className="podcast-placeholder-text">
              Podcast generating... Check back shortly.
            </p>
          </div>
        )}

        <p className="podcast-meta">
          Generated by Samantha, Best of Us Investors AI Analyst
        </p>
      </div>
    </section>
  );
}
